services:  
  customer:
    build:
      context: .
      dockerfile: ./apps/customer/Dockerfile
      target: development
    command: yarn run start:dev customer
    depends_on:
      - auth
    env_file:
      - ./apps/customer/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3004:3004'

  customer-info-receiver:
    build:
      context: .
      dockerfile: ./apps/customer-info-receiver/Dockerfile
      target: development
    command: yarn run start:dev customer-info-receiver
    depends_on:
      - auth
    env_file:
      - ./apps/customer-info-receiver/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  
  driver-status-tracker:
    build:
      context: .
      dockerfile: ./apps/driver-status-tracker/Dockerfile
      target: development
    command: yarn run start:dev driver-status-tracker
    depends_on:
      - auth
    env_file:
      - ./apps/driver-status-tracker/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  customer-address-positioning:
    build:
      context: .
      dockerfile: ./apps/customer-address-positioning/Dockerfile
      target: development
    command: yarn run start:dev customer-address-positioning
    depends_on:
      - auth
    env_file:
      - ./apps/customer-address-positioning/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  revenue:
    build:
      context: .
      dockerfile: ./apps/revenue/Dockerfile
      target: development
    command: yarn run start:dev revenue
    depends_on:
      - auth
    env_file:
      - ./apps/revenue/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn run start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      target: development
    command: yarn run start:dev admin
    env_file:
      - ./apps/admin/.env
    depends_on:
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3002:3002'
  
  driver:
    build:
      context: .
      dockerfile: ./apps/driver/Dockerfile
      target: development
    command: yarn run start:dev driver
    env_file:
      - ./apps/driver/.env
    depends_on:
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3003:3003'
      
  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #     - '5672:5672'